/* 
Now we create the UserClass containing the getters and setters
Create arraylist and put this list into the jtable using two methods/functions : 
1. show_on_table()
2. getUserList()
*/
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author San
 */
public final class MyFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame2
     */
    Connection conn;
    Statement stat;
    ResultSet rs;
    
    public MyFrame2() {
        initComponents();
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/student_info","root","");
            stat = conn.createStatement();
            JOptionPane.showMessageDialog(null,"connection established");                  
            show_on_table();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    
    public ArrayList<UserClass> getUserList(){
        ArrayList<UserClass> userList = new ArrayList<>();
        try{       
            UserClass user;
            rs = stat.executeQuery("SELECT * FROM `LIST`");
            while(rs.next()){
                user = new UserClass(rs.getInt("Id"),rs.getString("Name"),rs.getString("Faculty"),rs.getString("Contact"));                
                userList.add(user);
            }            
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
            System.exit(0);
        }
        return userList;
    }
    
    public void show_on_table(){
        ArrayList<UserClass> users = getUserList();                             //getUserList provides the necessary arraylist
        DefaultTableModel tableModel = (DefaultTableModel)table.getModel();     //this(jtable1) is our table name, u may right click on table and see change variable name or below this class
        Object[] rows = new Object[4];                                          //No. of colums = 4
        /*
        for(int i = 0; i < users.size(); i++){            
            rows[0] = users.get(i).getId();
            rows[1] = users.get(i).getName();
            rows[2] = users.get(i).getFaculty();
            rows[3] = users.get(i).getContact();            
            tableModel.addRow(rows);
        }
        */
        
        
        //Other way
        for(int i = 0; i < users.size(); i++){ 
            UserClass userdata = users.get(i);   //take ith index class from arraylist user
            rows[0] = userdata.getId();
            rows[1] = userdata.getName();
            rows[2] = userdata.getFaculty();
            rows[3] = userdata.getContact();            
            tableModel.addRow(rows);
        }
        
        
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameL = new javax.swing.JLabel();
        facultyL = new javax.swing.JLabel();
        contactL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        facultyTF = new javax.swing.JTextField();
        contactTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        insertB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        messageL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameL.setText("Name");

        facultyL.setText("Faculty");

        contactL.setText("Contact");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Faculty", "Contact"
            }
        ));
        jScrollPane1.setViewportView(table);

        insertB.setText("Insert");

        updateB.setText("Update");

        deleteB.setText("Delete");

        messageL.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(facultyL)
                                    .addComponent(contactL)
                                    .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(facultyTF, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(contactTF)))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateB, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(insertB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facultyL)
                    .addComponent(facultyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactL)
                    .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteB))
                .addGap(31, 31, 31)
                .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MyFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactL;
    private javax.swing.JTextField contactTF;
    private javax.swing.JButton deleteB;
    private javax.swing.JLabel facultyL;
    private javax.swing.JTextField facultyTF;
    private javax.swing.JButton insertB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageL;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTable table;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
